apiVersion: v2
name: valkey
description: A Helm chart for Valkey - High performance in-memory data structure store, fork of Redis
type: application
version: 0.1.0
appVersion: "8.1.3"
home: https://cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/charts/valkey
keywords:
  - valkey
  - redis
  - cache
  - database
  - keyvalue
  - inmemory
  - nosql
annotations:
  category: Database
  license: Apache-2.0
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://cloudpirates.io