{{- if and .Values.config.content (not .Values.config.existingConfigmap)}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  mongod.conf: |
    {{- .Values.config.content | nindent 4 }}
{{- end }}