{{- if .Values.auth.enabled }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.auth.rootPassword | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}
{{- end }}