{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescaledb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "timescaledb.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}