apiVersion: v2
name: mariadb
description: MariaDB is a high-performance, open-source relational database server that is a drop-in replacement for MySQL
type: application
version: 0.1.0
appVersion: "11.8.2"
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - relational
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/charts/mariadb

maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io

icon: https://a.storyblok.com/f/143071/512x512/6512dd22ee/mariadb-logo.svg