{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "postgres.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.enablePostgresUser }}
  postgres-password: {{ .Values.auth.postgresPassword | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  {{- if eq (include "postgres.createUser" .) "true" }}
  password: {{ .Values.auth.password | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
{{- end }}