{{- if and .Values.master.persistence.enabled (not .Values.master.persistence.existingClaim) (eq .Values.master.kind "Deployment") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" . }}-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
  {{- if or .Values.master.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.master.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.master.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.master.persistence.size | quote }}
  {{- if or .Values.master.persistence.storageClass .Values.global.storageClass }}
  storageClassName: {{ coalesce .Values.master.persistence.storageClass .Values.global.storageClass | quote }}
  {{- end }}
  {{- if .Values.master.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.master.persistence.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.master.persistence.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.master.persistence.dataSource "context" $) | nindent 4 }}
  {{- end }}
{{- end }}