{{- if .Values.auth.enabled }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "redis.fullname" .)) }}
  {{- $existingPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingPassword = index $existingSecret.data "redis-password" }}
  {{- end }}
  redis-password: {{ $existingPassword | default (.Values.auth.password | default (randAlphaNum 16) | b64enc) | quote }}
{{- end }}
{{- end }}