{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  {{ include "redis.secretPasswordKey" . }}: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  {{ include "redis.secretPasswordKey" . }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}