{{- if .Values.auth.enabled }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.auth.password | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}
{{- end }}