{{- if not .Values.config.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "valkey.annotations" . | nindent 4 }}
  {{- end }}
data:
  valkey.conf: |
    # Valkey configuration file
    
    # Network
    bind 0.0.0.0
    port {{ .Values.service.targetPort }}
    
    # General
    daemonize no
    supervised no
    
    # Logging
    loglevel notice
    logfile ""
    
    # Persistence
    dir {{ include "valkey.dataDir" . }}
    {{- if .Values.config.save }}
    save {{ .Values.config.save }}
    {{- else }}
    save ""
    {{- end }}
    
    # Memory management
    {{- if .Values.config.maxMemory }}
    maxmemory {{ .Values.config.maxMemory }}
    maxmemory-policy {{ .Values.config.maxMemoryPolicy }}
    {{- end }}
    
    # Security
    {{- if .Values.auth.enabled }}
    protected-mode yes
    {{- else }}
    protected-mode no
    {{- end }}
    
    # Additional configuration
    {{- range .Values.config.extraConfig }}
    {{ . }}
    {{- end }}
{{- end }}