{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "valkey.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.auth.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}