{{- if and (not .Values.auth.existingSecret) .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.rootPasswordKey }}: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- if or .Values.auth.username .Values.auth.password }}
  {{ .Values.auth.secretKeys.userPasswordKey }}: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}