{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "minio.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  root-user: {{ .Values.auth.rootUser | b64enc | quote }}
  root-password: {{ .Values.auth.rootPassword | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}