{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "minio.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "minio.fullname" .)) }}
  {{- $existingRootPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingRootPassword = index $existingSecret.data "root-password" }}
  {{- end }}
  root-user: {{ .Values.auth.rootUser | b64enc | quote }}
  root-password: {{ $existingRootPassword | default (.Values.auth.rootPassword | default (randAlphaNum 32) | b64enc) | quote }}
{{- end }}