apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: minio
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-console
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- $annotations := merge .Values.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consoleTargetPort }}
      protocol: TCP
      name: console
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}