apiVersion: v2
name: postgres
description: The World's Most Advanced Open Source Relational Database
type: application
version: 0.1.0
appVersion: "17.2"
keywords:
  - postgres
  - postgresql
  - database
  - sql
  - relational
home: https://cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/charts/postgres
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io