apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with (include "rabbitmq.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  rabbitmq.conf: |
    # Default RabbitMQ configuration
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    
    # Memory configuration
    vm_memory_high_watermark.{{ .Values.config.memoryHighWatermarkType }} = {{ include "rabbitmq.memoryHighWatermark" . }}
    
    # Disk space configuration
    disk_free_limit.absolute = {{ .Values.config.diskFreeLimit }}
    
    # Clustering configuration
    {{- if .Values.clustering.enabled }}
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.hostname_suffix = .{{ include "rabbitmq.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    cluster_formation.randomized_startup_delay_range.min = 0
    cluster_formation.randomized_startup_delay_range.max = 2
    {{- end }}
    
    # Logging configuration
    log.console = true
    log.console.level = info
    
    # Management plugin configuration will use default settings
    
    {{- if .Values.metrics.enabled }}
    # Prometheus metrics
    prometheus.tcp.port = {{ .Values.metrics.port }}
    {{- end }}
    
    {{- if .Values.ldap.enabled }}
    # LDAP authentication
    auth_backends.1 = rabbit_auth_backend_ldap
    auth_backends.2 = rabbit_auth_backend_internal
    auth_ldap.servers.1 = {{ .Values.ldap.server }}:{{ .Values.ldap.port }}
    auth_ldap.user_dn_pattern = {{ .Values.ldap.userDnPattern }}
    {{- end }}
    
    {{- if and .Values.config.extraConfiguration (ne .Values.config.extraConfiguration "") }}
    # Extra configuration
{{ .Values.config.extraConfiguration | indent 4 }}
    {{- end }}
    
  {{- if and .Values.config.advancedConfiguration (ne .Values.config.advancedConfiguration "") }}
  advanced.config: |
{{ .Values.config.advancedConfiguration | indent 4 }}
  {{- end }}
  
  enabled_plugins: |
    [rabbitmq_management{{- if .Values.clustering.enabled }},rabbitmq_peer_discovery_k8s{{- end }}{{- if .Values.metrics.enabled }},rabbitmq_prometheus{{- end }}].