apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with (include "rabbitmq.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.clustering.enabled }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
    - port: {{ .Values.service.epmdPort }}
      targetPort: epmd
      protocol: TCP
      name: epmd
    - port: {{ .Values.service.distPort }}
      targetPort: dist
      protocol: TCP
      name: dist
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}