apiVersion: v2
name: redis
description: An open source, in-memory data structure store used as a database, cache, and message broker.
type: application
version: 0.1.0
appVersion: "8.2.0"
keywords:
  - redis
  - database
  - cache
  - in-memory
  - key-value
  - nosql
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/charts/redis
annotations:
  category: Database
  license: Apache-2.0
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
icon: https://a.storyblok.com/f/143071/512x512/5d3310f00d/redis-logo.svg