{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clusterpirate.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
{{- toYaml .Values.serviceAccount.annotations | indent 4 }}
    {{- end }}
{{- include "clusterpirate.annotations" . | indent 4 }}
  {{- end }}
  {{- if .Values.commonLabels }}
  labels:
{{- include "clusterpirate.labels" . | indent 4 }}
  {{- end }}
{{- end }}